app:
  env: ${APP_ENV:development}
  name: microservices-template

http:
  port: 8080

grpc:
  port: 50051

database:
  host: localhost
  port: 5432
  name: microservices_db
  user: postgres
  password: postgres
  sslmode: disable

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
